/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#372400",
        "primary-fixed-dim": "#f66700",
        "on-tertiary": "#fff1df",
        "on-tertiary-fixed-variant": "#5e4000",
        "on-background": "#2c2f30",
        "inverse-on-surface": "#9b9d9e",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5c5b5b",
        "surface": "#f5f6f7",
        "primary-container": "#ff7a2f",
        "secondary-container": "#e5e2e1",
        "on-primary-fixed-variant": "#4f1c00",
        "surface-dim": "#d1d5d7",
        "inverse-surface": "#0c0f10",
        "surface-container-highest": "#dadddf",
        "on-error-container": "#520c00",
        "error-container": "#f95630",
        "on-secondary-fixed": "#403f3f",
        "secondary-fixed": "#e5e2e1",
        "primary-fixed": "#ff7a2f",
        "outline": "#757778",
        "on-error": "#ffefec",
        "tertiary-container": "#fbb423",
        "primary": "#9c3f00",
        "on-primary-container": "#401500",
        "inverse-primary": "#fe6b00",
        "tertiary": "#7a5400",
        "on-surface": "#2c2f30",
        "on-primary": "#fff0ea",
        "surface-container-high": "#e0e3e4",
        "on-secondary": "#f5f2f1",
        "surface-bright": "#f5f6f7",
        "tertiary-fixed": "#fbb423",
        "on-secondary-container": "#525151",
        "secondary-fixed-dim": "#d6d4d3",
        "surface-container-low": "#eff1f2",
        "tertiary-fixed-dim": "#eba60f",
        "on-tertiary-container": "#523700",
        "error": "#b02500",
        "outline-variant": "#abadae",
        "on-surface-variant": "#595c5d",
        "on-primary-fixed": "#000000",
        "background": "#f5f6f7",
        "on-secondary-fixed-variant": "#5c5b5b",
        "primary-dim": "#893600",
        "tertiary-dim": "#6b4900",
        "error-dim": "#b92902",
        "secondary-dim": "#504f4f",
        "surface-tint": "#9c3f00",
        "surface-variant": "#dadddf",
        "surface-container": "#e6e8ea"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [
    import('@tailwindcss/forms'),
    import('@tailwindcss/container-queries'),
  ],
}
